root: true
env:
  node: true
  vue/setup-compiler-macros: true
extends:
  - 'plugin:vue/vue3-essential'
  - 'eslint:recommended'
parserOptions:
  parser: '@babel/eslint-parser'
rules:
  no-unused-vars:
    - error
    - argsIgnorePattern: ^_

  vue/multi-word-component-names:
      - error
      - ignores:
          - Reg
          - Header
          - Default
          - Search
